version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command: [ "redis-server"]


