version: "3.5"
services:
    mongo:
        image: mongo:latest
        networks:
            - tasknet
        volumes:
            - mongodata:/data/db

    web:
        links:
            - mongo:mongo
        image: ${NEXUS_URL}/${PROJECT_NAME}:${TAG}
        ports:
            - 5000:5000
        depends_on:
            - mongo
        networks:
            - tasknet

networks:
    tasknet:
        name: tasknet
volumes:
    mongodata:
