version: "3.5"
services:
    redis:
        image: redis:latest
#        ports:
#            - 6379:6379
        networks:
            - tasknet
    mongo:
        image: mongo:latest
        networks:
            - tasknet
        volumes:
            - mongodata:/data/db

    web:
        links:
            - mongo:mongo
        image: ${NEXUS_URL}/${PROJECT_NAME}:${TAG}
        ports:
            - 5000:5000
        depends_on:
            - mongo
        networks:
            - tasknet

networks:
    tasknet:
        name: tasknet
volumes:
    mongodata:
