version: "3.5"
services:

    web:
        image: ${NEXUS_URL}/${PROJECT_NAME}:${TAG}
        ports:
            - 5000:5000
        depends_on:
            - mongo
            - redis
        networks:
            - tasknet

    mongo:
        image: mongo:latest
        networks:
            - tasknet
        volumes:
            - mongodata:/data/db

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - tasknet

networks:
    tasknet:
        name: tasknet
volumes:
    mongodata:
