version: '3'
services:
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        command: [ "redis-server"]
    mongo:
        image: mongo:lastest
        ports:
            - "27017:27017"
    web:
        links:
            - "mongo:mongo"
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongo
